
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = "https://zhvhqpdcxgmcdoowahql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodmhxcGRjeGdtY2Rvb3dhaHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njc5NjYsImV4cCI6MjA2MTI0Mzk2Nn0.yHH0jFSBqL-sCiSpVtMfTmF5OJV5SAbtpI7YCr8lyZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
